### ISSUE TITLE
Add TLS support for Prometheus communication

### ISSUE THREAD

**Issue by leonsery** [prometheus-community/postgres_exporter#454]
Please add TLS support for Prometheus communication like it already was done for : [node_exporter](inuits.eu/blog/prometheus-tls/)

**Comment by oliver-moore** [comment]
IT would be great if this also included basic user authentication along with TLS - again in line with node exporter - see https://developpaper.com/add-authentication-to-prometheus-node-exporter/

**Comment by SuperQ** [comment]
We've split out the TLS support into a separate package to make it easier:

https://github.com/prometheus/exporter-toolkit

**Comment by volker-raschek** [comment]
Hi, 
I would like to fix the bug as I would like to use TLS authentication and encryption for the metric endpoint in my kubernetes environment. 

Before I simply send a patch, I would like to know what requirements you, the maintainers, have for such a patch. I could solve this relatively quickly and customize the HTTP server so that it is possible to run it via TLS encryption (HTTPS). However, I understand that it would not be wrong to use the exporter-toolkit. This would probably lead to a breaking change, which I would like to avoid.

Please give me some feedback on how to solve the problem in your opinion, so that I can provide a patch in the near future.

**Comment by SuperQ** [comment]
This has already been fixed with https://github.com/prometheus-community/postgres_exporter/pull/491.
